services:
  micro-file-cache:
    image: bozonx/micro-file-cache:latest
    container_name: micro-file-cache
    ports:
      - '80:80'
    environment:
      - AUTH_TOKEN=your-secret-key
      - MAX_TTL_MIN=10080
      - MAX_FILE_SIZE_MB=100
      - MAX_STORAGE_SIZE_MB=1000
      - LOG_LEVEL=error
      - CORS_ORIGIN=true
      # More environment variables see in .env.example
    volumes:
      - file_cache_storage:/app/storage
    restart: unless-stopped
    networks:
      - micro-file-cache-network

volumes:
  file_cache_storage:
    driver: local

networks:
  micro-file-cache-network:
    driver: bridge
